"""
bitbucket_pr.py
Creates a Pull Request on Bitbucket (stash.r1dev.com) via REST API.
Only called when AUTO_PUSH=true in .env.

Bitbucket Server REST API:
  POST /rest/api/1.0/projects/{project}/repos/{repo}/pull-requests
"""

import os
import requests
from requests.auth import HTTPBasicAuth
from dotenv import load_dotenv

load_dotenv()

# ─── Config from .env ────────────────────────────────────────────────────────

BITBUCKET_URL      = os.getenv("BITBUCKET_URL", "https://stash.r1dev.com")
BITBUCKET_PROJECT  = os.getenv("BITBUCKET_PROJECT", "")   # e.g. R1OD
BITBUCKET_REPO     = os.getenv("BITBUCKET_REPO", "")      # e.g. routeone
BITBUCKET_USERNAME = os.getenv("BITBUCKET_USERNAME", "")
BITBUCKET_PASSWORD = os.getenv("BITBUCKET_PASSWORD", "")  # personal access token or password
BASE_BRANCH        = os.getenv("BASE_BRANCH", "QA")


def create_bitbucket_pr(ticket_id: str, title: str = None, description: str = None) -> dict:
    """
    Creates a PR on Bitbucket Server targeting BASE_BRANCH.

    Args:
        ticket_id:   Jira ticket ID e.g. R1OD-123
        title:       PR title — defaults to a standard message if not provided
        description: PR description — defaults to a standard message if not provided

    Returns:
        dict with success, pr_url, and any error details
    """
    # ── Validate config ───────────────────────────────────────────────────────
    missing = []
    if not BITBUCKET_PROJECT:  missing.append("BITBUCKET_PROJECT")
    if not BITBUCKET_REPO:     missing.append("BITBUCKET_REPO")
    if not BITBUCKET_USERNAME: missing.append("BITBUCKET_USERNAME")
    if not BITBUCKET_PASSWORD: missing.append("BITBUCKET_PASSWORD")
    if missing:
        msg = f"Missing Bitbucket config in .env: {', '.join(missing)}"
        print(f"\n❌ {msg}")
        return {"success": False, "error": msg}

    branch_name = f"feature/{ticket_id.lower()}"

    pr_title = title or f"{ticket_id}: AI generated implementation"
    pr_description = description or (
        f"This PR was automatically generated by the Agentic Development Platform.\n\n"
        f"**Jira Story:** {ticket_id}\n"
        f"**Source Branch:** `{branch_name}`\n"
        f"**Target Branch:** `{BASE_BRANCH}`\n\n"
        f"Please review the generated code and ensure it meets all acceptance criteria "
        f"before approving."
    )

    # ── Build API payload ─────────────────────────────────────────────────────
    api_url = (
        f"{BITBUCKET_URL}/rest/api/1.0/projects/{BITBUCKET_PROJECT}"
        f"/repos/{BITBUCKET_REPO}/pull-requests"
    )

    payload = {
        "title": pr_title,
        "description": pr_description,
        "state": "OPEN",
        "open": True,
        "closed": False,
        "fromRef": {
            "id": f"refs/heads/{branch_name}",
            "repository": {
                "slug": BITBUCKET_REPO,
                "project": {"key": BITBUCKET_PROJECT}
            }
        },
        "toRef": {
            "id": f"refs/heads/{BASE_BRANCH}",
            "repository": {
                "slug": BITBUCKET_REPO,
                "project": {"key": BITBUCKET_PROJECT}
            }
        },
        "locked": False,
        "reviewers": []   # No reviewers auto-added — team assigns manually
    }

    print(f"\n{'=' * 50}")
    print(f"🔀 Creating Bitbucket PR for {ticket_id}")
    print(f"{'=' * 50}")
    print(f"   URL     : {api_url}")
    print(f"   From    : {branch_name}")
    print(f"   To      : {BASE_BRANCH}")
    print(f"   Title   : {pr_title}")

    # ── Make API call ─────────────────────────────────────────────────────────
    try:
        response = requests.post(
            api_url,
            json=payload,
            auth=HTTPBasicAuth(BITBUCKET_USERNAME, BITBUCKET_PASSWORD),
            headers={"Content-Type": "application/json"},
            timeout=30,
            verify=False   # Internal Bitbucket servers often use self-signed certs
        )
    except requests.exceptions.ConnectionError:
        msg = f"Could not connect to Bitbucket at {BITBUCKET_URL} — are you on the VPN?"
        print(f"\n❌ {msg}")
        return {"success": False, "error": msg}
    except requests.exceptions.Timeout:
        msg = "Bitbucket API request timed out after 30s"
        print(f"\n❌ {msg}")
        return {"success": False, "error": msg}
    except Exception as e:
        msg = f"Unexpected error calling Bitbucket API: {e}"
        print(f"\n❌ {msg}")
        return {"success": False, "error": msg}

    # ── Handle response ───────────────────────────────────────────────────────
    if response.status_code == 201:
        pr_data = response.json()
        pr_id   = pr_data.get("id", "")
        pr_url  = (
            f"{BITBUCKET_URL}/projects/{BITBUCKET_PROJECT}"
            f"/repos/{BITBUCKET_REPO}/pull-requests/{pr_id}"
        )
        print(f"\n✅ PR created successfully!")
        print(f"   PR #{pr_id}: {pr_url}")
        return {
            "success": True,
            "pr_id": pr_id,
            "pr_url": pr_url,
            "branch": branch_name,
            "target": BASE_BRANCH
        }

    elif response.status_code == 409:
        # PR already exists for this branch
        msg = f"A PR already exists for branch '{branch_name}'"
        print(f"\n⚠️  {msg}")
        return {"success": False, "error": msg, "status_code": 409}

    else:
        msg = f"Bitbucket API returned {response.status_code}: {response.text[:300]}"
        print(f"\n❌ {msg}")
        return {"success": False, "error": msg, "status_code": response.status_code}


# ─── CLI Test ─────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import sys
    if len(sys.argv) < 2:
        print("Usage: py bitbucket_pr.py <ticket_id>")
        print("Example: py bitbucket_pr.py R1OD-123")
        sys.exit(1)

    result = create_bitbucket_pr(sys.argv[1])
    print(f"\nResult: {result}")